---
docker:
  user: ubuntu
  groups:
  - docker

additional_packages:
- unrar

optional_tasks:
  setup_compose: true
  compose_basedir: docker
  compose_file_dirs:
  - coredns
  - coredns/config
  - coredns/config/zones
  compose_file:
    composeVersion: "3.7"
    restartPolicy: always
    containers:
      coredns:
        enabled: true
        tag: "1.10.0"
        memoryLimit: 500M
        memoryReservation: 250M
        prometheus:
          enabled: true
        datadog:
          enabled: true
    environment:
      TZ: "America/Chicago"

dns:
  zones:
    donthurt.us:
    - name: webmail
      ttl: 360
      type: A
      record: 165.227.198.53
    - name: _dmarc
      ttl: 1400
      type: TXT
      record: 'v=DMARC1\; p=none'
    - name: donthurt.us.
      ttl: 1400
      type: TXT
      record: "v=spf1 include:_spf.protonmail.ch mx ~all"
    - name: protonmail._domainkey
      ttl: 360
      type: CNAME
      record: protonmail.domainkey.dj57gimeviwdkoszrvhx7ncym4qynnlv4zlln7qd53y6h7xbx3qrq.domains.proton.ch.
    - name: protonmail2._domainkey
      ttl: 360
      type: CNAME
      record: protonmail2.domainkey.dj57gimeviwdkoszrvhx7ncym4qynnlv4zlln7qd53y6h7xbx3qrq.domains.proton.ch.
    - name: protonmail3._domainkey
      ttl: 360
      type: CNAME
      record: protonmail3.domainkey.dj57gimeviwdkoszrvhx7ncym4qynnlv4zlln7qd53y6h7xbx3qrq.domains.proton.ch.
    - name: donthurt.us.
      ttl: 1400
      type: TXT
      record: 'protonmail-verification=adb491a754659e7da8dd3983fc978c361304ae5e'
    - name: donthurt.us.
      ttl: 360
      type: MX
      priority: 10
      record: mail.protonmail.ch.
    - name: donthurt.us.
      ttl: 360
      type: MX
      priority: 20
      record: mailsec.protonmail.ch.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-1324.awsdns-37.org.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-1736.awsdns-25.co.uk.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-221.awsdns-27.com.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-746.awsdns-29.net.
    - name: donthurt.us.
      ttl: 360
      type: NS
      record: dns1.donthurt.us.
    - name: donthurt.us.
      ttl: 360
      type: NS
      record: dns2.donthurt.us.
