---
docker:
  user: ubuntu
  groups:
  - docker

additional_packages:
- unrar

optional_tasks:
  setup_compose: true
  compose_basedir: docker
  compose_file_dirs:
  - coredns
  - coredns/config
  - coredns/config/zones
  compose_file:
    composeVersion: "3.7"
    restartPolicy: always
    containers:
      coredns:
        enabled: true
        tag: "1.10.0"
        memoryLimit: 500M
        memoryReservation: 250M
        prometheus:
          enabled: true
        datadog:
          enabled: true
    environment:
      TZ: "America/Chicago"
