---
docker:
  user: ubuntu
  groups:
  - docker

additional_packages:
- unrar

optional_tasks:
  setup_compose: true
  compose_basedir: docker
  compose_file_dirs:
  - coredns
  - coredns/config
  compose_file:
    composeVersion: "3.7"
    restartPolicy: always
    containers:
      coredns:
        enabled: true
        memoryLimit: 500M
        memoryReservation: 250M
        cpuLimit: 0.3
    environment:
      TZ: "America/Chicago"
