---
docker:
  user: ubuntu
  groups:
  - docker

additional_packages:
- unrar

optional_tasks:
  setup_compose: true
  compose_basedir: docker
  compose_file_dirs:
  - coredns
  - coredns/config
  - coredns/config/zones
  compose_file:
    composeVersion: "3.7"
    restartPolicy: always
    containers:
      coredns:
        enabled: true
        memoryLimit: 500M
        memoryReservation: 250M
        prometheus:
          enabled: true
        datadog:
          enabled: true
    environment:
      TZ: "America/Chicago"

dns:
  zones:
    donthurt.us:
    - name: mail
      ttl: 360
      type: A
      record: 165.227.198.53
    - name: imap
      ttl: 360
      type: A
      record: 165.227.198.53
    - name: webmail
      ttl: 360
      type: A
      record: 165.227.198.53
    - name: cpanel
      ttl: 360
      type: A
      record: 165.227.198.53
    - name: _dmarc
      ttl: 1400
      type: TXT
      record: 'v=DMARC1\; p=reject\; sp=none\; rf=afrf\; pct=100\; ri=86400'
    - name: donthurt.us.
      ttl: 1400
      type: TXT
      record: "v=spf1 +a +mx +ip4:165.227.198.53 +mx:mail.donthurt.us +ip4:198.49.77.166 +ip4:198.49.77.167 +ip4:198.49.77.171 -all"
    - name: default._domainkey
      ttl: 1400
      type: TXT
      record: 'v=DKIM1\; k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6s6H2dPhvt4TGmf6IKe0JfRC896/V4tjL/GMgEtwGUZ5ki0gb+/GpY22f5U7zESnFm1kOEBlErhipvCtJpIkajPJq2d0uftKVb/4M37IBCaB0wLxLkt8JEySAsdDViSOrA50MPHgC0AUbk7x5gJomJcUBzcuV8UP1kw+lKx0CaUUW5xI7Vv8t4VhS/XOwUqjeRbc6jQddYV/9VzRiaaqWhRmjlY9r1RBHWHHQVyqdiEVr3KZLBf99Z2AsvKLV1PCEp8OYrrrS/xAvrD3hnB2M6AA/baKsi2s1BwXaFxxkTbj6ZT+X+pOZYjbQipQaY4y3OhygAQCZOpBqOAfyG6EtQIDAQAB'
    - name: donthurt.us.
      ttl: 360
      type: MX
      priority: 0
      record: mail.donthurt.us.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-1324.awsdns-37.org.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-1736.awsdns-25.co.uk.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-221.awsdns-27.com.
    - name: k8s
      ttl: 1400
      type: NS
      record: ns-746.awsdns-29.net.
    - name: donthurt.us.
      ttl: 360
      type: NS
      record: dns1.donthurt.us.
    - name: donthurt.us.
      ttl: 360
      type: NS
      record: dns2.donthurt.us.
