---
docker:
  user: ubuntu
  groups:
  - docker

additional_packages:
- unrar

optional_tasks:
  setup_compose: true
  compose_basedir: docker
  compose_file_dirs:
  - coredns
  - coredns/config
  - coredns/config/zones
  compose_file:
    composeVersion: "3.7"
    restartPolicy: always
    containers:
      coredns:
        enabled: true
        memoryLimit: 500M
        memoryReservation: 250M
    environment:
      TZ: "America/Chicago"

dns:
  zones:
    donthurt:
    - name: dns1
      ttl: 60
      type: A
      record: 5.161.183.35
    - name: dns2
      ttl: 60
      type: A
      record: 5.161.154.26
    - name: mail
      ttl: 360
      type: A
      record: 165.227.198.53
    - name: donthurt.us.
      ttl: 360
      type: MX
      priority: 0
      record: mail.donthurt.us.
    - name: k8s.donthurt.us.
      ttl: 360
      type: NS
      record: ns-1324.awsdns-37.org.
    - name: k8s.donthurt.us.
      ttl: 360
      type: NS
      record: ns-1736.awsdns-25.co.uk.
    - name: k8s.donthurt.us.
      ttl: 360
      type: NS
      record: ns-221.awsdns-27.com.
    - name: k8s.donthurt.us.
      ttl: 360
      type: NS
      record: ns-746.awsdns-29.net.
