---
- name: "Configure DNS Server"
  gather_facts: yes
  hosts: all
  vars_files:
    - group_vars/all.yaml
    - group_vars/dns-zones.yaml
  tasks:
    - assert:
        that:
        - "ansible_distribution == 'Ubuntu'"
        fail_msg: "This playbook contains apt specific tasks that will not work on non-Ubuntu systems"
    - import_tasks: tasks/docker-user.yaml
    - import_tasks: tasks/compose-docker.yaml
    - import_tasks: tasks/coredns.yaml
      when: optional_tasks.setup_compose is true

  handlers:
  - name: "restart-docker"
    service:
      name: docker
      state: restarted
      enabled: yes
  - name: "restart-datadog"
    service:
      name: datadog-agent
      state: restarted
      enabled: yes
