---
- name: "Create compose directories"
  file:
    state: directory
    recurse: no
    path: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/{{ item }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0755
  with_items:
    - "{{ optional_tasks.compose_file_dirs }}"