---
- name: "Copy Docker compose file"
  template:
    src: docker-compose.yaml.j2
    dest: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/coredns/docker-compose.yaml"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0600

- name: "Copy CoreDNS config"
  template:
    src: Corefile.j2
    dest: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/coredns/config/Corefile"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0600

- name: "Copy DNS zones"
  template:
    src: zones/{{ item }}.zone.j2
    dest: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/coredns/config/zones/{{ item }}"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0600
  with_items:
  - donthurt.us

- name: "Install pip3"
  package:
    name: python3-pip
    state: latest

- name: "Install Python Docker SDK"
  pip:
    name:
    - docker
    - docker-compose

- name: "Disable systemd-resolved"
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: "Configure resolv.conf"
  copy:
    src: resolv.conf
    dest: /run/systemd/resolve/stub-resolv.conf
    owner: root
    group: root
    mode: 0644

- name: "Start containers"
  community.docker.docker_compose:
    project_src: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/coredns"
    build: no
    pull: yes

- name: "Fix file and directory ownership"
  file:
    path: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/coredns"
    recurse: yes
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
  changed_when: no

- name: "Install additional packages"
  package:
    state: latest
    name: "{{ additional_packages }}"
