---
- name: "Copy media stack Docker compose file"
  template:
    src: media-stack.yaml.j2
    dest: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/media_stack/docker-compose.yaml"
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
    mode: 0600

- name: "Install pip3"
  package:
    name: python3-pip
    state: latest

- name: "Install Python Docker SDK"
  pip:
    name:
    - docker
    - docker-compose

- name: "Start containers"
  community.docker.docker_compose:
    project_src: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/media_stack"
    build: no
    pull: yes

- name: "Fix file and directory ownership"
  file:
    path: "{{ homedir }}/{{ optional_tasks.compose_basedir }}/media_stack"
    recurse: yes
    owner: "{{ docker.user }}"
    group: "{{ docker.user }}"
  changed_when: no

- name: "Install additional packages"
  package:
    state: latest
    name: "{{ additional_packages }}"