---
- name: "Load Datadog variables"
  include_vars:
    dir: ../group_vars
    extensions:
      - 'yaml'

- name: "Include Datadog Galaxy role"
  include_role:
    name: datadog.datadog
  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_agent_major_version: "7"
    datadog_config:
      tags:
        "{{ custom.tag }}"
      env: prod
      inventories_configuration_enabled: true
      logs_enabled: true
      logs_config:
        container_collect_all: false
      process_config:
        process_collection:
          enabled: true
        container_collection:
          enabled: true
        process_discovery:
          enabled: true
      system_probe_config:
        enabled: true
        network_probe:
          enabled: true
  with_items:
  - { tag: "{{ baseTags }}" }
  loop_control:
    loop_var: custom
  tags:
  - install-datadog

- name: "Setup dd-agent user for Docker commands"
  user:
    name: dd-agent
    groups: docker
    append: yes

- name: "Create .ssh directory"
  file:
    state: directory
    recurse: no
    path: "/opt/datadog-agent/.ssh"
    owner: "{{ sshConfig['user'] }}"
    group: "{{ sshConfig['user'] }}"
    mode: 0700

- name: "Create dd-agent SSH key"
  openssh_keypair:
    path: "{{ sshConfig['sshKey'] }}"
    size: 4096
    type: rsa
  register: ssh_key

- name: "Add dd-agent SSH key to authorized_keys"
  authorized_key:
    user: "{{ sshConfig['user'] }}"
    state: present
    key: "{{ ssh_key.public_key }}"

- name: "Fix file and directory ownership"
  file:
    path: "/opt/datadog-agent/.ssh"
    recurse: yes
    owner: "{{ sshConfig['user'] }}"
    group: "{{ sshConfig['user'] }}"
  changed_when: no

- name: "Copy Datadog Configuration Files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "dd-agent"
    group: "dd-agent"
    mode: 0640
  with_items:
  - { src: 'datadog-docker.yaml.j2', dest: '/etc/datadog-agent/conf.d/docker.d/conf.yaml' }
  - { src: 'datadog-disk.yaml.j2', dest: '/etc/datadog-agent/conf.d/disk.d/conf.yaml' }
  - { src: 'datadog-systemd.yaml.j2', dest: '/etc/datadog-agent/conf.d/systemd.d/conf.yaml' }
  - { src: 'datadog-ssh.yaml.j2', dest: '/etc/datadog-agent/conf.d/ssh_check.d/conf.yaml' }
  - { src: 'datadog-ntp.yaml.j2', dest: '/etc/datadog-agent/conf.d/ntp.d/conf.yaml' }
  notify:
  - restart-datadog
