---
name: Ansible

on:
  pull_request:
    branches: [master, main]

env:
  PLAYBOOK: main.yaml
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  ANSIBLE_DEPRECATION_WARNINGS: 'false'

jobs:
  ansible-dry-run:
    name: Run Ansible Playbook (dry run)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run playbook
        uses: arillso/action.playbook@master
        with:
          playbook: ${{ env.PLAYBOOK }}
          inventory: remote-inventory
          galaxy_file: ansible-requirements.yaml
          private_key: ${{ secrets.RSA_KEY_MAIN }}
          vault_password: ${{ secrets.ANSIBLE_VAULT }}
          check: true
          diff: true
          skip_tags: datadog
     # - name: Run playbook
     #   uses: dawidd6/action-ansible-playbook@v2
     #   with:
     #     # Required, playbook filepath
     #     playbook: ${{ env.PLAYBOOK }}
     #     # Optional, directory where playbooks live
     #     directory: ./
     #     # Optional, SSH private key
     #     key: ${{ secrets.RSA_KEY_MAIN }}
     #     # Optional, literal inventory file contents
     #     inventory: |
     #       [all]
     #       5.161.154.26 ansible_user=root ansible_port=22

     #     # Optional, SSH known hosts file content
     #     # Optional, encrypted vault password
     #     vault_password: ${{ secrets.ANSIBLE_VAULT }}
     #     # Optional, galaxy requirements filepath
     #     requirements: ansible-requirements.yaml
     #     # Optional, additional flags to pass to ansible-playbook
     #     options: |
     #       --verbose
     #       --check
     #       --diff